name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  qa:
    name: Rust Quality Assurance
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Format
      run: cargo fmt --check
      
    - name: Check
      run: cargo check
      
    - name: Clippy
      run: cargo clippy
